### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional value (inData)

### ISSUE THREAD

**Issue by meismyles** [tidwall/IoniconsSwift#9]
In `ionicons.swift`, my project crashes when it attempts to execute this line:

**Line 20**: `let inData = try? Data(contentsOf: URL(fileURLWithPath: Bundle(identifier: "com.oncast.IoniconsSwift")!.path(forResource: "ionicons", ofType: "ttf")!))`

Crash:
_**fatal error: unexpectedly found nil while unwrapping an Optional value**_

**Comment by zzycami** [comment]
Also have this problem, when use cocospod to use oniconsSwift in Xcode8, cocospod version 1.1.0.beta.2. to solve this problem , I add source code and ttf file to my project rename Bundle.main. but all the icon become ...

**Comment by zzycami** [comment]
Find the problem , add ! at line 53,

```
public var description : String {
        return String(describing: UnicodeScalar(rawValue)!)
    }
```

**Comment by meismyles** [comment]
This doesn't solve the problem for me

**Comment by zzycami** [comment]
Add the source code and ttf file to your project, then change to this.

```
private func load(){
    if loaded {
        return
    }
    loaded = true
    let inData = try? Data(contentsOf: URL(fileURLWithPath: Bundle.main.path(forResource: "ionicons", ofType: "ttf")!))
    var error : Unmanaged<CFError>?
    let provider = CGDataProvider(data: inData as! CFData)
    let font = CGFont(provider!)
    if !CTFontManagerRegisterGraphicsFont(font, &error) {
        let errorDescription = CFErrorCopyDescription(error!.takeRetainedValue())
        NSLog("Failed to load font: %@", errorDescription as! String);
    }
}
```

**Comment by tidwall** [comment]
I pushed an update that address the "..." issue that @zzycami mentions. 

@meismyles 

> **Line 20:** let inData = try? Data(contentsOf: URL(fileURLWithPath: Bundle(identifier: "com.oncast.IoniconsSwift")!.path(forResource: "ionicons", ofType: "ttf")!))

I'm not seeing this problem on my side. Are you using CocoaPods?

**Comment by meismyles** [comment]
@tidwall Yep, using CocoaPods.

I've tried specifically using the `master` branch, the `swift/3.0` branch, and also using the latest version of CocoaPods and the Pre-release version CocoaPods but always getting the same issue.

**Comment by zzycami** [comment]
master is ok, I think this update work fine, we can close this discuss.

**Comment by meismyles** [comment]
Yep, this issue seems fixed with the latest commit. Closing this for now.
